services:

  backend1:
    image: dovecot/dovecot:2.4-latest
    container_name: backend1
    restart: unless-stopped
    ports:
      - "127.0.0.1:1143:31143/tcp"
      - "127.0.0.1:2424:31024/tcp"
    volumes:
      - ./docker/local.conf:/etc/dovecot/conf.d/local.conf:ro
      - shared:/srv/mail

  backend2:
    image: dovecot/dovecot:2.4-latest
    container_name: backend2
    restart: unless-stopped
    ports:
      - "127.0.0.1:2143:31143/tcp"
      - "127.0.0.1:3424:31024/tcp"
    volumes:
      - ./docker/local.conf:/etc/dovecot/conf.d/local.conf:ro
      - shared:/srv/mail

volumes:
  shared:
